apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec: 
  type: NodePort
  ports:
    - port: 80
      #targetPort: 80 é definido como sendo igual ao primeiro se for definido só o port
      nodePort: 30000
  selector:
    app: primeiro-pod